### ISSUE TITLE
Contribute upstream?

### ISSUE THREAD

**Issue by mfkl** [nima64/VLC-3-lua-extension-guide#1]
Hi,

Thanks for this useful guide.

It would be great to get this contributed upstream. What do you think?

We're building some new docs websites. You could contribute your Lua section to https://code.videolan.org/ePirat/devdocs.

https://docs.videolan.me/vlc-user
https://epirat.videolan.me/devdocs/

Thanks!

**Comment by nima64** [comment]
Yes I would love too! : )

**Comment by mfkl** [comment]
Great, feel free to open MRs :)
